name: Assign User on Comment

on:
  issue_comment:
    types: [created]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "/assigntome" in comment
        uses: actions/github-script@v3.1.0
        with:
          token: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
          script: | 
            const issueComment = context.payload.comment.body;
            const assignRegex = /\/assigntome/i;
            if assignRegex.test(issueComment)) {
            const assignee = context.payload.comment.user.login;
            const issueNumber = context.payload.issue.number;
            const octokit = require('@octokit/rest')();
            octokit.authenticate({
              type: 'token',
              token: process.env.GITHUB_TOKEN
            });
            octokit.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              assignees: [assignee]
            });
          }
