name: Label pull requests

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Propagate labels to pull requests
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.issue;
            const issueNumber = issue.number;
            const issueLabels = issue.labels.map(label => label.name);
            
            // Get the pull requests that reference the issue
            const { data: pullRequests } = await github.rest.issues.listEvents({
              owner: issue.owner,
              repo: issue.repo,
              issue_number: issueNumber
            });
            
            for (const event of pullRequests) {
              if (event.event === 'cross-referenced' && event.source && event.source.issue && event.source.issue.pull_request) {
                const prNumber = event.source.issue.number;
                
                // Add labels to the pull request
                await github.rest.issues.addLabels({
                  owner: issue.owner,
                  repo: issue.repo,
                  issue_number: prNumber,
                  labels: issueLabels
                });
              }
            }
