name: Label pull requests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Propagate labels to pull requests
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
        with:
          script: |
            const issue = context.issue;
            const issueNumber = issue.number;
            const issueLabels = issue.labels && issue.labels.length > 0 ? issue.labels.map(label => label.name) : [];
            
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: issue.owner,
              repo: issue.repo,
              state: 'open',
              head: `${issue.owner}:${issueNumber}`,
            });   
            for (const pullRequest of pullRequests) {
              // Add labels to each pull request
              await github.rest.issues.addLabels({
                owner: pullRequest.base.user.login,
                repo: pullRequest.base.repo.name,
                issue_number: pullRequest.number,
                labels: issueLabels
              });
            }
