name: Label pull requests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Propagate labels to pull requests
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const prBody = context.payload.pull_request.body
            const matchIssue = prBody.match(/#(\d+)/)
            if (!matchIssue || matchIssue.length <= 1) {
              console.log('No issues are associated with this PR found')
            }
            else {
              const linkedIssue = matches[1]
              const labels = await github.rest.issues.listLabelsOnIssue({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: linkedIssue
              })
              if(labels.data.length == 0) {
                console.log(`No labels on the issue #${linkedIssue}`)
              }
              else {
                const labels = labels.data.map(item => item.name)
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: labels
                })
                console.log('Adding labels', labels)
              }
            }
