name: Label pull requests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Propagate labels to pull requests
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const name: Label Sync

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync labels
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context, github } = require('@actions/github');

            const prNumber = context.payload.pull_request.number;

            const { data: prData } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            const issueRef = prData.body.match(/Fixes #(\d+)/);
            if (!issueRef) {
              console.log('No issue reference found in the PR body');
              return;
            }

            const issueNumber = issueRef[1];

            const { data: issueData } = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
            });

            const labels = issueData.labels.map((label) => label.name);

            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels,
            });

