name: Label pull requests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Propagate labels to pull requests
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
        with:
          script: |
            const issue = context.issue;
            const issueNumber = issue.number;
            const issueLabels = issue.labels.map(label => label.name);
            
            await github.rest.issues.addLabels({
              owner: pullRequest.base.user.login,
              repo: pullRequest.base.repo.name,
              issue_number: pullRequest.number,
              labels: issueLabels
            });
