name: Label pull requests

on:
  workflow_dispatch:
  issues:
    types:
      - reopened
      - opened

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Propagate labels to pull requests
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.issue;
            const issueNumber = issue.number;
            const issueLabels = issue.labels.map(label => label.name);
            
            // Get the pull requests that reference the issue
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: issue.owner,
              repo: issue.repo,
              state: 'open'
            });
            
            for (const pullRequest of pullRequests) {
              const prNumber = pullRequest.number;
              
              const { data: issueComments } = await github.rest.issues.listComments({
                owner: pullRequest.base.user.login,
                repo: pullRequest.base.repo.name,
                issue_number: prNumber
              });
              
              const issueReferenced = issueComments.some(comment => comment.body.includes(`#${issueNumber}`));
              
              if (issueReferenced) {
                await github.rest.issues.addLabels({
                  owner: pullRequest.base.user.login,
                  repo: pullRequest.base.repo.name,
                  issue_number: prNumber,
                });
              }
            }
