name: Label pull requests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Propagate labels to pull requests
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { pull_request: pr } = context.payload;

            const issueRef = pr.body.match(/#(\d+)/);
            if (!issueRef) {
              console.log('No issue reference found in the PR body');
              return;
            }

            const issueNumber = issueRef[1];

            const { data: issueData } = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
            });

            const labels = issueData.labels.map((label) => label.name);

            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels,
            });
