name: Leaderboard

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run leaderboard script
      run: |
        python3 ./.github/workflows/leaderboard-pytorch-docathon.py
    - name: push
      uses: actions-x/commit@v6
      with: 
        branch: main
        directory: ./
