name: Labeler

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  generate_content_label:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}   

    steps:
    - name: User Nutrition Label
      uses: lbonanomi/nutrition-label@1.1
      with:
        count-forked: 'false'
