# This is a basic workflow to help you get started with Actions

name: Page Ge

# Controls when the workflow will run
on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "55 23 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tutorial-age:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run script
        run: |
          git ls-tree -r master --name-only | grep -E '.*\.(rst|py)' | while read filename; do 
           echo "$(git log -1 --date=short --format="%ad" -- $filename) $filename";
          done | sort -r | tr  " " ","  > file.csv
      # Runs a set of commands using the runners shell
      - name: push
        uses: actions-x/commit@v6    
        with: 
          branch: main
          directory: ./
          token: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
