name: Leaderboard PyTorch Docathon

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run leaderboard script
      run: |
        python3 .github/scripts/pytorch-docathon-h2-2023.py
    - name: push
      uses: actions-x/commit@v6
      with: 
        branch: main
        directory: ./
