name: github-repo-stats

on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "55 23 * * 0"
  workflow_dispatch: # Allow for running this manually.

jobs:
  traffic:
    name: github-repo-stats
    runs-on: ubuntu-latest
    steps:
    - name: Run pull request stats
      uses: flowwer-dev/pull-request-stats@master
    - name: Checkout
      uses: actions/checkout@v2
    - name: Collect traffic
      uses: sangonzal/repository-traffic-action@v.0.1.6
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
        REPOSITORY_NAME: "pytorch/examples"
    - name: push
      uses: actions-x/commit@v6    
      with: 
        branch: main
        directory: ./traffic
        token: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
