name: github-repo-stats

on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  j1:
    name: github-repo-stats
    runs-on: ubuntu-latest
    steps:
      - name: set envs
        env:
          INPUT_GHTOKEN: ${{ secrets.ghrs_github_api_token }}
          INPUT_DATABRANCH: github-repo-stats
          INPUT_REPOSITORY: pytorch/examples
          INPUT_GHPAGESPREFIX: none
          GHRS_TESTING: true
          GHRS_FILES_ROOT_PATH: /
        # Use latest release.
        uses: jgehrcke/github-repo-stats@v1.4.1
        with:
          repository: pytorch/examples
          # databranch: github-repo-stats 
          ghtoken: ${{ secrets.ghrs_github_api_token }}
