name: github-repo-stats

on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "55 23 * * 0"
  workflow_dispatch: # Allow for running this manually.

jobs:
  traffic:
    name: github-repo-stats
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: "github-repo-stats"

    - name: Collect traffic
      uses: sangonzal/repository-traffic-action@v.0.1.6
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
        REPOSITORY_NAME: "pytorch/examples"
    - name: pull
      run: |
        git pull origin github-repo-stats --allow-unrelated-histories 
    - name: push
      uses: actions-x/commit@v6    
      with: 
        branch: github-repo-stats
        directory: ./traffic
        token: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
