# This is a basic workflow to help you get started with Actions

name: Test stats

# Controls when the workflow will run
on:
  #schedule:
  # Run this once per day.
  #  - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-tutorials-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Test
        run: |
           pip3 install pandas
           pip3 install boto3
           pip3 install typing
           pip3 install awswrangler
      - name: Test
        run: |
           bash
           ls
