name: Reminder to submit PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
  
jobs:
  check-assignment:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install @octokit/rest
        run: |
          npm i @octokit/core @octokit/rest
      - name: Install @actions/github
        run: |
          npm i @actions/github
      - name: Check for "/assigntome" in comment
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
        with:
          script: | 
            const { Octokit } = require("@octokit/rest");
            
            async function run() {
              const octokit = new Octokit({auth: process.env.GITHUB_TOKEN});
              
              const { context } = require("@actions/github");
              const { owner, repo, issue } = context.repo;
              
              const { data: comments } = await octokit.issues.listComments({
                owner,
                repo,
                issue_number: issue.number,
              });
            
              const assignComment = comments.find(comment => comment.body.includes("/assigntome"));
            
              if (assignComment) {
                const CommentCreatedAt = new Date(assignComment.created_at);
                const twoDaysAgo = new Date();
                twoDaysAgo.setDate(twoDaysAgo.getDate() - 2);
              
                if (commentCreatedAt < twoDaysAgo) {
                  const newCommentBody = "This issue was assigned more than 2 days ago. Please submit a PR ASAP."
                  await octokit.issues.createComment({
                    owner,
                    repo,
                    issue_number: issue.number,
                    body: newCommentBody
                  });
                }
              }
            }
            run();
