name: Reminder to submit PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
  
jobs:
  check-assignment:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install @octokit/rest
        run: |
          npm i @octokit/core @octokit/rest
      - name: Install @actions/github
        run: |
          npm i @actions/github
      - name: Check for "/assigntome" in comment
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
        with:
          script: | 
            const issueComment = context.payload.comment.body;
            const assignRegex = /\/assigntome/i;
            if (assignRegex.test(issueComment)) {
              const commentCreatedAt = new Date(context.payload.comment.created_at);
              const twoDaysAgo = new Date();
              twoDaysAgo.setDate(twoDaysAgo.getDate() - 2);
              if (commentCreatedAt < twoDaysAgo) {
                const assignee = context.payload.comment.user.login;
                const octokit = context.github;
                const { owner, repo } = context.repo;
                octokit.issues.createComment({
                  owner: owner,
                  repo: repo,
                  issue_number: context.issue.number,
                  body: `This issue was assigned 2 or more days ago and no PR was sent. Please submit your PR ASAP.`
                });
              }
            }
