name: Reminder to submit PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  check-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check comments and post updates
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
        with:
          script: |
            const twoDaysAgo = new Date();
            twoDaysAgo.setDate(twoDaysAgo.getDate() - 2);
            async function getComments(issueNumber) {
              const response = await github.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber
              });
              return response.data;
            }
            async function getPullRequests(issueNumber) {
              const response = await github.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open'
              });
              return response.data;
            }
            async function postComment(issueNumber, body) {
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: body
              });
            }
            async function checkIssueComments() {
              const response = await github.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open'
              });
              const issues = response.data;
              for (const issue of issues) {
                if (issue.assignee) {
                  const comments = await getComments(issue.number);
                  const reminderCommentExists = comments.some(comment => comment.body.includes("It's been more than 2 days since this issue was assigned."));
                  if (!reminderCommentExists) {
                    const pullRequests = await getPullRequests(issue.number);
                    if (pullRequests.length === 0) {
                      for (const comment of comments) {
                        const commentDate = new Date(comment.created_at);
                        if (commentDate < twoDaysAgo && comment.body.includes('/assigntome')) {
                          const message = `@${issue.user.login} It's been more than 2 days since this issue was assigned. Please submit a PR ASAP.`;
                          await postComment(issue.number, message);
                        }
                      }
                    }
                  }
                }
              }
            }
            await checkIssueComments();
