name: Unassign issues with no PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run script to check and unassign issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/github-script@v4
        with:
          script: |
            async function run() {
              try {
                const threeDaysAgo = new Date();
                threeDaysAgo.setDate(threeDaysAgo.getDate() - 3);

                const issues = await github.issues.listForRepo({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: 'open',
                  labels: 'test',
                  assignee: '*'
                });

                for (const issue of issues.data) {
                  const assignedAt = new Date(issue.assignee.updated_at);

                  if (assignedAt > threeDaysAgo) {
                    const pullRequests = await github.pulls.list({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      state: 'open',
                      base: `refs/issues/${issue.number}`,
                    });

                    if (pullRequests.data.length === 0) {
                      await github.issues.removeAssignees({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: issue.number,
                        assignees: [issue.assignee.login],
                      });

                      await github.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: issue.number,
                        body: 'This issue was unassigned due to inactivity. If you are still interested in working on this issue, please feel free to reassign it to yourself and submit a pull request ASAP.',
                      });
                    }
                  }
                }
              } catch (error) {
                console.error(error);
              }
            }

            run();
